name: testAndBuildAndPush

on:
  push:
    branches: [ master ]

jobs:
  buildAndPush:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/checkout@v2
      - name: Use Node.js 12.18
        uses: actions/setup-node@v1
        with:
          node-version: 12.18
          
      - name: Run tests
        run: npm test

      - name: Grant executable permission to buildImage
        run: chmod +x ci/buildImage.sh
      - name: Build and push docker image
        run: ./ci/buildImage.sh
