name: prTest

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.18
        uses: actions/setup-node@v1
        with:
          node-version: 12.18
      - name: Set up react scripts
        run: npm install react-scripts@3.4.1 -g --silent
      - name: Run tests
        run: npm test --passWithNoTests
